version: "3.9"

services:
  # DATABASE
  postgres:
    image: postgres:alpine
    container_name: postgres_login
    restart: always
    ports:
      - "5432:5432"
    tty: true
    environment:
      POSTGRES_USER: kindone
      POSTGRES_DB: kindone
      POSTGRES_PASSWORD: Parola#@!123
  pgadmin:
    container_name: pgadmin4_login
    image: dpage/pgadmin4:7.0
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5000:80"
  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    volumes:
      - ./backend:/app
    depends_on:
      - postgres
    ports:
      - "3001:3001"
  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    volumes:
      - ./frontend:/app
    depends_on:
      - backend
    ports:
      - "3000:3000"